version: "3"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # use local conf
      - ./sock:/nginx/sock:rw                  # expose unix domain sockets
      - ../frontend/build:/srv/frontend:ro     # expose React "static" build
    networks:
      default:
        aliases:
          - radio
