version: "3"

services:
  frontend:
    build:
      context: ../frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DEV: 1
      DJENIUS_SOCKET_HOST: nginx:80
    networks:
      - radio

  backend:
    build:
      context: ../
    restart: unless-stopped
    ports:
      - "7000:8000"
    environment:
      DEBUG: 1
      BACKEND: 1
      MPV: mpv:6600
      RESOLVER: resolver:8000
    networks:
      - radio

  resolver:
    build:
      context: ../
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DEBUG: 1
      BACKEND: 0
    networks:
      - radio

  mpv:
    build:
      context: ./mpv/
    restart: unless-stopped
    ports:
      - "6600:6600"
    networks:
      - radio

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # use local conf
      - ./sock:/nginx/sock:rw # expose unix domain sockets
      - ../frontend/build:/srv/frontend:ro # expose React "static" build
    networks:
      - radio

networks:
  radio:
    name: radio
