global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: []

  - job_name: 'djenius'
    scrape_interval: 5s
    static_configs:
      - targets:
        - localhost:9090
